name: SoundPlayer
version: 1.0
author: thutson3876
main: me.thutson3876.fantasyclasses.SoundPlayer
description: A plugin development tool to easily test various Minecraft sound effects
api-version: 1.19

commands:
  playsound:
    usage: /<command> <sound> <volume> <pitch>
    description: plays sound at player location with the specified volume and pitch